---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name }}-svc
  labels:
    app: {{ .Values.zookeeper.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.zookeeper.containerPort1 }}
      targetPort: {{ .Values.zookeeper.containerPort1 }}
      protocol: TCP
      name: {{ .Values.zookeeper.name }}-1
    - port: {{ .Values.zookeeper.containerPort2 }}
      targetPort: {{ .Values.zookeeper.containerPort2 }}
      protocol: TCP
      name: {{ .Values.zookeeper.name }}-2
    - port: {{ .Values.zookeeper.containerPort3 }}
      targetPort: {{ .Values.zookeeper.containerPort3 }}
      protocol: TCP
      name: {{ .Values.zookeeper.name }}-3


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name }}-svc
  labels:
    app: {{ .Values.kafka.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.kafka.name }}
  ports:
    - port: {{ .Values.kafka.containerPort }}
      targetPort: {{ .Values.kafka.containerPort }}
      protocol: TCP
      name: {{ .Values.kafka.name }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.connect.name }}-svc
  labels:
    app: {{ .Values.connect.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.connect.name }}
  ports:
    - port: {{ .Values.connect.containerPort }}
      targetPort: {{ .Values.connect.containerPort }}
      protocol: TCP
      name: {{ .Values.connect.name }}
